#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# load gruvbox color
~/.vim/bundle/gruvbox/gruvbox_256palette_osx.sh


# load coreutils
export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
alias ls='ls -F --show-control-chars --color=auto'
eval `gdircolors -b $HOME/.dir_colors`

export CLICOLOR=1
export TERM=xterm-256color


#alias
alias ll='ls -alhF'
alias la='ls -AF'
alias l='ls -CF'
alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"

#alias mvim="open -a MacVim"
alias vi='vim'
alias v='mvim'
alias nodeg='node --harmony-generators'

#alias rm
alias rm='rm -riv'
alias mv='mv -i'

# sublime text
alias e='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl* . &'

#add rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# add nvm
if [[ -s "$HOME/.nvm/nvm.sh" ]] ; then
  source "$HOME/.nvm/nvm.sh" ;
  #source "$HOME/.nvm/bash_completion" ;
fi
alias cnpm="npm --registry=http://r.cnpmjs.org"

#add go
export GOPATH=$HOME/golang
export PATH=$PATH:$GOPATH/bin

# bundler rails
alias be='bundle exec'
alias rails='bundle exec rails'

#ctags
alias gtags='ctags -R --fields=+l .'
alias erltags='ctags -R --fields=+l --languages=erlang .'
alias rbtags='ctags -R --fields=+l --languages=ruby --exclude=.bundle .'
alias rubytags='ripper-tags -R --exclude=.bundle'

alias zshup='cd ~/.zprezto && git pull && git submodule update --init --recursive && source ~/.zshrc && cd -'
alias zshreload='source ~/.zshrc'

